# 1. Validation trong Nodejs
## 1.1. Giới thiệu
`Validation` là một phần quan trọng trong một ứng dụng, nó giúp chúng ta kiểm tra dữ liệu đầu vào từ người dùng trước khi lưu vào database. 

Trong Nodejs, chúng ta có thể sử dụng thư viện `express-validator` để thực hiện việc này.

Sử dụng `express-validator`, chúng ta có thể thay thế `connect-flash` và `express-session` để hiển thị thông báo lỗi cho người dùng.

## 1.2. Cài đặt
Để cài đặt thư viện `express-validator`, chúng ta sử dụng lệnh sau:
```bash
npm install express-validator
```

## 1.3. Sử dụng
`express-validator` cung cấp 2 phương thức chính để kiểm tra dữ liệu:
- `check()`: Kiểm tra dữ liệu từ request. Chúng ta sử dụng `check()` kết hợp với các hàm kiểm tra sau để kiểm tra dữ liệu, lưu ý có thể sử dụng nhiều hàm kiểm tra trong một `check()`, và có thể `validate` nhiều dữ liệu trong một request bằng cách truyền vào một mảng các `check()` và đặt trước `middleware` xử lý `req, res, next` của route.
    + `isEmail(<email>)`: Kiểm tra xem dữ liệu có phải là email hay không.
    + `isLength({min: <min>, max: <max>})`: Kiểm tra xem dữ liệu có độ dài từ `min` đến `max` hay không.
     +`isNumber(<value>)`: Kiểm tra xem dữ liệu có phải là số hay không.
    + `isAlpha(<value>)`: Kiểm tra xem dữ liệu có phải là chữ cái hay không.
    + `isAlphanumeric(<value>)`: Kiểm tra xem dữ liệu có phải là chữ cái hoặc số hay không.
    + `isInt(<value>)`: Kiểm tra xem dữ liệu có phải là số nguyên hay không.
    + `isFloat(<value>)`: Kiểm tra xem dữ liệu có phải là số thực hay không.
    + `isIn(<array>)`: Kiểm tra xem dữ liệu có nằm trong mảng `array` hay không.
    + `isURL(<url>)`: Kiểm tra xem dữ liệu có phải là URL hay không.
    + `isISO8601(<date>)`: Kiểm tra xem dữ liệu có phải là ngày tháng theo chuẩn ISO8601 hay không.
    + `isAfter(<date>)`: Kiểm tra xem dữ liệu có phải là ngày tháng sau ngày `date` hay không.
    + `isBefore(<date>)`: Kiểm tra xem dữ liệu có phải là ngày tháng trước ngày `date` hay không.
    + `equals(<value>)`: Kiểm tra xem dữ liệu có bằng với `value` hay không.
    + `custom(<function>)`: Kiểm tra dữ liệu theo hàm `function`. Hàm `function` nhận vào 2 tham số `value` (dữ liệu cần kiểm tra từ request) và `meta` (bao gồm `req`, `location`, `path`). Hàm `function` trả về `true` nếu dữ liệu hợp lệ và `false` nếu dữ liệu không hợp lệ.
    + `exists()`: Kiểm tra xem dữ liệu có tồn tại hay không.
    + `isEmpty()`: Kiểm tra xem dữ liệu có rỗng hay không.
    + `not()`: Phủ định kết quả của hàm kiểm tra.
    + `optional()`: Bỏ qua kiểm tra nếu dữ liệu không tồn tại.
    + `withMessage(<message>)`: Thêm thông báo lỗi nếu dữ liệu không hợp lệ.
    + `normalizeEmail()`: Chuẩn hóa email.
    + `trim()`: Loại bỏ khoảng trắng ở đầu và cuối dữ liệu.
    + `escape()`: Loại bỏ các ký tự đặc biệt.
    + `blacklist(<chars>)`: Loại bỏ các ký tự trong `chars`.
    + `whitelist(<chars>)`: Loại bỏ các ký tự không nằm trong `chars`.
- `validationResult()`: Với tham số truyền vào là request, phương thức này sẽ trả về một giá trị, chứa thông tin về các lỗi xảy ra trong quá trình kiểm tra dữ liệu. Ta có thể chuyển giá trị này thành một mảng các lỗi bằng cách sử dụng phương thức `array()`. Và các thành phần trong mảng này sẽ chứa thông tin về lỗi, bao gồm `msg`, `param`, `location`, ...

## 1.4. Ví dụ sử dụng `express-validator`
Ta sẽ tạo một hàm đăng ký tài khoản, trong đó kiểm tra dữ liệu đầu vào từ người dùng:

1. Tạo một file `auth.js` trong thư mục `routes`:
    > File routes/auth.js
    ```javascript
    const express = require('express');
    const { check, validationResult } = require('express-validator');
    const router = express.Router();

    route.post(
    "/signup",
    [
        // Kiểm tra username đã tồn tại chưa
        check("username")
        .trim() // Loại bỏ khoảng trắng ở đầu và cuối dữ liệu của người dùng khi nhập vào
        .notEmpty()  // Kiểm tra xem người dùng có để trống username không, nếu để trống thì trả về thông báo "Please don't leave the blank username" được thể hiện trong hàm withMessage()
        .withMessage("Please don't leave the blank username") 
        .custom((value, { req }) => { // Kiểm tra xem username đã tồn tại trong database chưa 
            // value là giá trị của username (req.body.username), req là request
            return User.findOne({ username: value }).then((usernameFound) => {
            // Tìm kiếm username trong database
            if (usernameFound) {
                // Nếu tìm thấy username
                return Promise.reject(
                // Thì reject và gán vào thuộc tính msg của {validationResult} giá trị bên trong hàm reject(), vì các hàm của moongose trả về promise
                "Username is existed, Please enter the another username"
                );
            }
            });
        }),
        // kiểm tra req.body.email nhập vào có phải là 1 email hợp lệ không
        // -> Nếu không hợp lệ, giá trị bên trong hàm withMessage() sẽ được gán vào thuộc tính msg của {validationResult}
        check("email", "Please enter the valid email") // Nếu bất kỳ hàm kiểm tra nào không thỏa mãn thì sẽ trả về thông báo "Please enter the valid email" cho `validationResult`
        .normalizeEmail() // Chuẩn hóa email
        .notEmpty() // Kiểm tra xem người dùng có để trống email không
        .isEmail()  // Kiểm tra xem email có phải là email không
        .custom((value, { req }) => { // Kiểm tra xem email đã tồn tại trong database chưa
            return User.findOne({ email: value }).then((emailFound) => {
            if (emailFound) {
                return Promise.reject(
                "Email is existed, Please sign up with another email"
                ); // Nếu tìm thấy email thì reject và gán vào thuộc tính msg của {validationResult} giá trị bên trong hàm reject()
            }
            }); // Nếu không tìm thấy email thì không làm gì cả
        }),

        check("password", "The password must be at least 5") // Nếu bất kỳ hàm kiểm tra nào không thỏa mãn thì sẽ trả về thông báo "The password must be at least 5" cho `validationResult`
        .trim()
        .isLength({ min: 5 }), // Độ dài mật khẩu tối thiểu là 5

        // Kiểm tra password và re_password có giống nhau không
        check("re_password")
        .trim()
        .custom((value, { req }) => {
            // value là giá trị của re_password (req.body.re_password), req là request
            if (value !== req.body.password) {
            // Nếu giá trị của re_password khác với giá trị của password
            throw new Error("Password and Re-Password do not match"); // Thì throw error và gán vào thuộc tính msg của {validationResult}
            }
            return true; // Nếu không có lỗi thì return true
        }),
    ],
    getAuth.postSignup
    );
    ```
2. Tạo một file `authController.js` trong thư mục `controllers` để xử lý `validation` nếu `validation` không hợp lệ:
    > File controllers/authController.js
    ```javascript
    const { validationResult } = require("express-validator"); // Import {validationResult} từ thư viện express-validator để lấy ra các lỗi từ request xử lý ở file routes/auth.js
    const User = require("../models/User");

    const postSignup = (req, res, next) => {
        const username = req.body.username; // Lấy giá trị username từ form
        const email = req.body.email; // Lấy giá trị email từ form
        const password = req.body.password; // Lấy giá trị password từ form
        const re_password = req.body.re_password; // Lấy giá trị re_password từ form
        // {Thêm phần nhập request vào hàm validationResult để kiểm tra với hàm check bên routes/auth} //
        const errorValidation = validationResult(req);
        // Nếu tồn tại lỗi trong việc xác thực giá trị nhập vào (email không hợp lệ, pass ko đủ độ dài và không == vs rePass)
        // {VALIDATION} //
        if (!errorValidation.isEmpty()) { // Nếu có lỗi thì trả về mảng các lỗi
            console.log(errorValidation.array()); // In ra mảng các lỗi
            const [error] = errorValidation.array(); // Lấy phần tử đầu tiên của mảng lỗi để hiển thị lỗi đầu tiên
            return res.status(422).render("./auth/signup", {
            title: "Sign Up",
            path: "/signup",
            error: error.msg, // Nếu có lỗi thì giá trị sẽ được tìm thấy ở thuộc tính "msg" (đã được gán trong hàm check() ở file routes/auth.js)
            errorType: error.path, // xác định trường nào lõi cần sửa (username, email, password, re_password)
            oldInput: { username, email, password, re_password }, // Lưu lại các giá trị vừa nhập
            });
            // Nếu lỗi email nhập vào không phải là email hợp lệ (VD: qqq)
            /*
                [
                {
                    type: 'field',
                    value: 'qqq',
                    msg: 'Invalid value',
                    path: 'email',
                    location: 'body'
                }
                ]
            */
        }
       // Tiếp tục xử lý nếu không có lỗi
    }
    ```
3. Tạo một file `signup.ejs` trong thư mục `views/auth` để hiển thị thông báo lỗi:
    > File views/auth/signup.ejs
    ```html
        <!-- VALIDATION INPUT -->
        <% if(error) { %>  <!-- Nếu có trả về trường `error` thì hiển thị thông báo lỗi -->
            <div class="message message--error">
                <%= error %>
            </div>
        <% } %>
        <!--  -->
    ```

# 2. Error Handling trong Nodejs
## 2.1. Giới thiệu
Khi 1 server chạy, chúng ta có các loại lỗi sau:
- Lỗi về mạng / kỹ thuật bên máy chủ (MongoDB, Redis, RabbitMQ, ...) bị sập
    - Các lỗi này thường không thể xử lý được, chỉ có thể thông báo cho người dùng biết (render ra một trang thông báo lỗi)
- Lỗi dự kiến, mong đợi: ví dụ như lỗi nhập sai mật khẩu, nhập sai email, lỗi truy cập vào một tài nguyên không có quyền truy cập, ...
    - Các lỗi này có thể xử lý được, có thể thông báo cho người dùng biết, thử lại hoặc chuyển hướng người dùng đến một trang khác
- Lỗi logic, bug: Do lỗi trong code, trong quá trình dev, ví dụ như lỗi chia cho 0, lỗi truy cập vào một phần tử không tồn tại trong mảng, ...
    - Các lỗi này không nên báo cho người dùng biết, mà nên báo cho dev biết để fix

## 2.2. Hoạt động và cách xử lý khi có lỗi
- Với các `hàm`, lỗi được ném ra bằng `throw`, và được bắt bằng `try catch` (giống như các ngôn ngữ khác) 
- Với các `route`, lỗi được ném ra bằng `next(error)`, và được bắt bằng `app.use((error, req, res, next) => { ... })` (middleware xử lý lỗi)
- Với các `promise`, lỗi được ném ra bằng `reject`, và được bắt bằng `.catch(error => { ... })`
> Như vậy, chúng ta có thể sửa trực tiếp lỗi trong `try catch`, hoặc nếu bắt lỗi bằng `next(error)` để chuyển hướng đến `middleware là app.use((error, req, res, next))` xử lý lỗi.
> Cách nhận biết `middleware` xử lý lỗi là `app.use((error, req, res, next) => { ... })` là do nó có 4 tham số, tham số đầu tiên là `error`.
> Nếu không có lỗi nào được ném ra bởi throw, bắt bằng try cacth, then,..

Ví dụ, kiểm tra xác thực đầu vào có phải là cáv giá trị hợp lệ hay không
- Nếu không  => Ném ra lỗi bằng throw, reject, next(error),...
- Nếu có     => Tiếp tục xử lý

## 2.3. Xử lý lỗi trong Nodejs bằng `try catch`
Ví dụ, khi chúng ta muốn kiểm tra `token` của người dùng có hợp lệ hay không, nếu không thì render ra một trang thông báo lỗi:
```javascript
const checkAuth = (req, res, next) => {
    try {
        const token = req.headers.authorization.split(" ")[1]; // Lấy token từ header
        const decoded = jwt.verify(token, process.env.JWT_SECRET); // Giải mã token
        req.userData = decoded; // Lưu thông tin user vào req
        next(); // Tiếp tục xử lý
    } catch (error) { // Nếu có lỗi thì bắt lỗi
        return res.status(401).json({
            message: "Auth failed",
        }); // Trả về thông báo lỗi
    }
};
```

## 2.4. Xử lý lỗi trong Nodejs bằng `next(error)` và `middleware xử lý lỗi` kết hợp với `try catch`
Ví dụ, khi chúng ta muốn kiểm tra `token` của người dùng có hợp lệ hay không, nếu không thì chuyển hướng người dùng đến trang thông báo lỗi, thì ta sẽ truyền lỗi vào `next(error)` và xử lý lỗi trong `middleware`:

`Middleware` sẽ nhận vào 4 tham số, tham số đầu tiên là `error`, tham số này được truyền vào từ hàm `next()`.

1. Tạo một `middleware` xử lý lỗi, trong file `app.js`: (Lưu ý, cần đặt `middleware` xử lý lỗi ở cuối cùng của file `app.js` để có thể xử lý tất cả các lỗi)
    > File `app.js`
    ```javascript
    // ... End of file
    // {ERROR MIDDLEWARE} // (Phải đặt ở cuối cùng) // Nếu không có lỗi thì sẽ chạy qua các middleware trước, nếu có lỗi thì sẽ chạy qua middleware này
    app.use((error, req, res, next) => { // Middleware có 4 tham số, tham số đầu tiên là error là middleware xử lý lỗi
        res.status(error.httpStatusCode) // Trả về status code của lỗi được truyền vào từ next(error)
        .render("500", { // Render ra trang "500"
            title: "Server maintenance", // Tiêu đề trang
            path: "/500", // Đường dẫn
        });
    });
    /// !!! Lưu ý: Nếu có lỗi thì phải truyền lỗi vào next() để nó chạy qua middleware này, nếu không thì nó sẽ chạy qua các middleware tiếp theo mà không có lỗi

    ```

2. Sử dụng `next(error)` để chuyển hướng người dùng đến trang thông báo lỗi:
    ```javascript
    const checkAuth = (req, res, next) => {
        try {
            const token = req.headers.authorization.split(" ")[1]; // Lấy token từ header
            const decoded = jwt.verify(token, process.env.JWT_SECRET); // Giải mã token
            req.userData = decoded; // Lưu thông tin user vào req
            next(); // Tiếp tục xử lý
        } catch (error) { // Nếu có lỗi thì bắt lỗi
            error.httpStatusCode = 401; // Gán status code cho lỗi
            return next(error); // Chuyển hướng người dùng đến trang thông báo lỗi
        }
    };
    ```